package com.ohgiraffers.handlermethod.legal;

public enum LegalNextStep {
    COLLECT_BASIC_FACTS,
    ORGANIZE_EVIDENCE_TIMELINE,
    ORGANIZE_CLAIM_AMOUNT_AND_EVIDENCE_TIMELINE,
    CHECK_DEADLINE_AND_LIMITATION_PERIOD,
    PREPARE_LAWYER_CONSULTATION_PACKET,
    ESCALATE_URGENT_REVIEW
}
